name: CI
on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: Integration
    strategy:
      matrix:
        os:
          - ubuntu-latest
        target:
          - aarch64-linux
          - aarch64-macos
          - aarch64-windows
          - x86_64-linux
          - x86_64-windows
        optimize:
          - ReleaseSmall
          - ReleaseFast
          - ReleaseSafe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2
        with:
          version: '0.17.0'

      - name: Get source code
        uses: actions/checkout@v2

      - name: Lint
        run: zig fmt --check --ast-check build.zig.zon build.zig src examples

      - name: Build (${{ matrix.target }}-${{ matrix.optimize }})
        if: matrix.os == 'ubuntu-latest'
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}

      - name: Tests
        run: zig build --summary all test
