name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          github-token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ci
          path: ntz

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./ntz/*.tar.gz
